export const mockPackageJsonObject = {
  repoInfo: { name: "@prodigytech/js-dependency-check", version: "5.0.0" },
  dependencies: [
    { package: "@babel/preset-env", version: "^7.18.2" },
    { package: "app-root-path", version: "^3.0.0" },
    { package: "axios", version: "^0.27.2" },
    { package: "babel-jest", version: "^28.1.1" },
    { package: "cli-table", version: "^0.3.11" },
    {  "package": "command-line-args", "version": "^5.2.1"},
    { package: "eslint-config-airbnb", version: "^19.0.4" },
    { package: "eslint-config-prettier", version: "^8.5.0" },
    { package: "eslint-plugin-import", version: "^2.26.0" },
    { package: "eslint-plugin-jsx-a11y", version: "^6.5.1" },
    { package: "eslint-plugin-node", version: "^11.1.0" },
    { package: "eslint-plugin-prettier", version: "^4.0.0" },
    { package: "semver", version: "7.3.7" },
  ],
  peerDependencies: [],
  devDependencies: [
    { package: "@semantic-release/changelog", version: "^6.0.1" },
    { package: "@semantic-release/exec", version: "^6.0.3" },
    { package: "@semantic-release/git", version: "^10.0.1" },
    { package: "rollup-plugin-terser", version: "^7.0.2" },
    { package: "semantic-release", version: "^19.0.2" },
    { package: "eslint", version: "^8.17.0" },
    { package: "jest", version: "^28.0.1" },
  ],
};
